### ISSUE TITLE
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

### ISSUE THREAD

**Issue by aiertamundarain** [camenduru/4DGaussians-colab#2]

**Comment by patrickjdarrow** [comment]
Encountered this as well using the colab demo.

The command
```
!python train.py -s /content/test/data/bouncingballs \
--port 6017 \
--expname "dnerf/bouncingballs" \
--configs arguments/dnerf/bouncingballs.py 
```
yields
```
/content/4DGaussians
Traceback (most recent call last):
  File "/content/4DGaussians/train.py", line 17, in <module>
    from gaussian_renderer import render, network_gui
  File "/content/4DGaussians/gaussian_renderer/__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'
```
